package Interface;

import Domain.CopyImagetoClipBoard;
import Domain.showImage;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author jeanp
 */
public class jp_imageArea extends javax.swing.JPanel {

    BufferedImage image, bufferSubimage;//imagen total
    Graphics2D graphics2D;
    boolean clicked = false;
    int x, y;
    
    private FileNameExtensionFilter fileFilter = new FileNameExtensionFilter("Archivo de imagen", "jpg", "png");
    JFileChooser chooser;
    CopyImagetoClipBoard copyImage = new CopyImagetoClipBoard();
    showImage showI = new showImage(x, y);
        
    public jp_imageArea() throws IOException {
        initComponents();
        

        /*-------------Obtener coordenadas del mouse-----------------*/
        addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                x = e.getPoint().x;
                y = e.getPoint().y;

                clicked = true;
                bufferSubimage = image.getSubimage(x, y, 100, 100);
                copyImage.copyImage(bufferSubimage);
                repaint();

                String name = String.format("[%d, %d]",
                        y, x);
                System.out.println(name);
            }
        });

    }//constructor
    
    public void showI() throws IOException{
        this.chooser = showI.showChooser();
        File file = chooser.getSelectedFile();
        repaint();
        add(showI);
    }
    
    

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);

        /*----------pinta la imagen completa--------*/
        graphics2D = (Graphics2D) g;
        graphics2D.drawImage(image, 0, 0, null);

        /*----------pinta el cuadro--------*/
        if (clicked) {
            g.setColor(Color.YELLOW);
            g.drawRect(x, y, 100, 100);
        }
    }//paint

//AutoGeneratedCode
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
